spring:
   profiles: dev
   datasource:
      url: jdbc:h2:./test
      username: root
      password:
      driverClassName: org.h2.Driver
      data: classpath:/scripts/data.sql
   jpa:
     database: h2
     hibernate:
       ddl-auto: create
     show-sql: true